### PR TITLE
Renew the function subset_matches() in Class Subsetter

### PR DESCRIPTION
**Pull request by algopert**
closes https://github.com/lukasalexanderweber/stitching/issues/50

### CODE REVIEW

**Comment by algopert** [comment]
Resolved this issue!
https://github.com/lukasalexanderweber/stitching/issues/50

**Comment by lukasalexanderweber** [comment]
can you eleborate on where exactly the bug was and how you solved it?

**Comment by lukasalexanderweber** [comment]
I really like your approach of getting rid of get_indices_to_delete(), subset_matrix(), delete_index_from_matrix() .

I updated the subset_matches and tests to make it more compact. Please check if it works for your issue and then I think we are ready to merge :)

**Comment by algopert** [comment]
Hi Lukas.

It works well.
I think there was error in either of 3 functions deleted.

By the way, I have a question.

There will be still the values smaller than threshold in matrix **matches_subset**.

image

By my simulation, it doesn't seem to affect the results.
Anyway, I will open another issue for that.

Let's merge.

Thanks.

**Review by algopert — COMMENTED** [review]
I think np.ix_() is good approach.

And I don't have a PYTHONic mindset, just trying to reduce computational complexity as an algo developer.

:)

**Review by algopert — COMMENTED** [review]
Very compact solution!

**Comment by lukasalexanderweber** [comment]
Thanks a lot for your contribution!

**Pull request merged**
