### PR TITLE
Update pre-commit config file

### PR DESCRIPTION
**Pull request by sadikkuzu**
Update pre-commit config file with latest hook versions

### CODE REVIEW

**Comment by lukasalexanderweber** [comment]
Have you checked if this results in any changes using `pre-commit run --all-files`?

**Comment by sadikkuzu** [comment]
No changes after `pre-commit run --all-files`
image

**Comment by lukasalexanderweber** [comment]
Nice thank you very much!

**Comment by sadikkuzu** [comment]
My pleasure 🙏🏼

**Pull request merged**
